name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Compile SASS
        run: npx sass style.sass style.css --style=compressed --no-source-map && npx sass fonts.sass fonts.css --style=compressed --no-source-map

      - name: Clean up
        run: |
          rm -f style.sass
          rm -f fonts.sass
          rm -f LICENSE-CODE
          rm -f LICENSE-FONTS
          rm -f LICENSE-CONTENT
          rm -f .gitignore

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
